class Files {
    public String fileName;
    public String fileExtension;
    public String content;
    public String parentFolder;

    public Files(String fileName, String fileExtension, String content, String parentFolder) {
        this.fileName = fileName;
        this.fileExtension = fileExtension;
        this.content = content;
        this.parentFolder = parentFolder;
    }

    public String getLifetimeBandwidthSize() {
        return string;
    }

    public String prependContent(String data) {
        return string;
    }

    public String addContent(String data, int Position) {
        return String;
    }

    public String showFileLocation() {
        return string;
    }
}